// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzdxzstovwapdslabqlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6ZHh6c3RvdndhcGRzbGFicWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDY2MzAsImV4cCI6MjA3MDY4MjYzMH0.ph6xCjypaQ3cZjD0H9mcBwM9pkwkAnzz6NbP46LFCvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});